name: poetry-test
on: [push, pull_request]
jobs:
  testing-poetry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Run poetry image 
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: "1.1.15"
      - name: poetry install requirements
        run: poetry install
      - name: shiny running
        run: | 
          poetry run shiny run app.py &
          sleep 5 &
          kill %% 
          